/**
 * functions/src/process-template-file.ts
 *
 * Cloud Function to process uploaded .docx and .pdf template files.
 * Downloads the file from Firebase Storage, extracts text/HTML,
 * and uses AI to smart-detect template variables and map them to
 * questionnaire fields.
 */

import { onCall, HttpsError } from 'firebase-functions/v2/https';
import * as admin from 'firebase-admin';
import mammoth from 'mammoth';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PDFParse } = require('pdf-parse');
import { callAI, parseAIJson } from './ai-client';
import { getLearningContext, formatLearningPrompt, recordCorrection, recordConfirmedVariables } from './template-learning';

// ---------------------------------------------------------------------------
// Helper: truncate text at a word boundary
// ---------------------------------------------------------------------------
function truncateAtWordBoundary(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  const truncated = text.slice(0, maxLen);
  const lastSpace = truncated.lastIndexOf(' ');
  return lastSpace > maxLen * 0.8 ? truncated.slice(0, lastSpace) + '…' : truncated + '…';
}

// ---------------------------------------------------------------------------
// Available questionnaire fields (for AI context)
// ---------------------------------------------------------------------------

const AVAILABLE_FIELDS = `
AVAILABLE QUESTIONNAIRE FIELDS (dot-path notation):

personalInfo.firstName, personalInfo.middleName, personalInfo.lastName, personalInfo.suffix
personalInfo.dob, personalInfo.ssnLast4, personalInfo.address, personalInfo.city
personalInfo.state, personalInfo.zip, personalInfo.county, personalInfo.email
personalInfo.phone, personalInfo.maritalStatus, personalInfo.citizenship
personalInfo.occupation, personalInfo.employer

spouseInfo.firstName, spouseInfo.middleName, spouseInfo.lastName
spouseInfo.dob, spouseInfo.email, spouseInfo.phone
spouseInfo.address, spouseInfo.city, spouseInfo.state, spouseInfo.zip

children[] — array of: { name, dob, isMinor, relationship, specialNeeds, guardian, alternateGuardian }

fiduciaries.executor.primary.name, fiduciaries.executor.primary.relationship, fiduciaries.executor.primary.address
fiduciaries.executor.alternate.name, fiduciaries.executor.alternate.relationship
fiduciaries.executor.successor.name
fiduciaries.executor.bondRequired, fiduciaries.executor.compensation

fiduciaries.trustee.primary.name, fiduciaries.trustee.primary.relationship
fiduciaries.trustee.alternate.name, fiduciaries.trustee.successor.name

fiduciaries.powerOfAttorney.agent.name, fiduciaries.powerOfAttorney.agent.relationship
fiduciaries.powerOfAttorney.agent.address, fiduciaries.powerOfAttorney.agent.city, fiduciaries.powerOfAttorney.agent.state, fiduciaries.powerOfAttorney.agent.zip
fiduciaries.powerOfAttorney.alternateAgent.name, fiduciaries.powerOfAttorney.alternateAgent.relationship
fiduciaries.powerOfAttorney.effectiveDate, fiduciaries.powerOfAttorney.giftingAuthority
fiduciaries.powerOfAttorney.powers[]

fiduciaries.healthcareProxy.primary.name, fiduciaries.healthcareProxy.primary.relationship
fiduciaries.healthcareProxy.alternate.name
fiduciaries.healthcareProxy.lifeSupport, fiduciaries.healthcareProxy.nutrition
fiduciaries.healthcareProxy.painManagement, fiduciaries.healthcareProxy.organDonation

fiduciaries.guardian.primary.name, fiduciaries.guardian.alternate.name

distribution.residualDistributions[] — { recipient, recipientRelationship, percentage, perStirpes, alternateRecipient }
distribution.specificBequests[] — { description, recipient, condition, alternateRecipient }
distribution.charitableBequests[] — { organizationName, ein, amount, percentage, purpose }
distribution.trustName, distribution.pourOverToTrust, distribution.noContestClause
distribution.spendthriftProvision, distribution.survivorshipPeriod

assets.realEstate[] — { address, type, currentValue, ownershipType, mortgageBalance }
assets.investments[] — { institution, accountType, estimatedValue }
assets.insurance[] — { company, policyType, deathBenefit, beneficiary }
assets.digitalAssets[] — { name, type }

specialConsiderations.hasSpecialNeedsChild, specialConsiderations.specialNeedsDetails
specialConsiderations.hasPetProvision, specialConsiderations.petDetails, specialConsiderations.petCaretaker

COMPUTED FIELDS (generated by system, not from questionnaire):
clientFullName, spouseFullName, hasSpouse, hasMinorChildren, hasSpecialNeedsChild
childCount, minorChildren[], adultChildren[], propertyCount
propertiesForTrust[], estimatedTotalAssets, primaryTrustName
todayFormatted, todayISO, packageType, packageLabel
`;

// ---------------------------------------------------------------------------
// Cloud Function
// ---------------------------------------------------------------------------

export const processTemplateFile = onCall(
  { region: 'us-east1', memory: '1GiB', timeoutSeconds: 120 },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, storagePath, fileName } = request.data as {
      firmId: string;
      storagePath: string;
      fileName: string;
    };

    if (!firmId || !storagePath || !fileName) {
      throw new HttpsError('invalid-argument', 'firmId, storagePath, and fileName are required.');
    }

    // Validate role
    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can process templates.');
    }

    const ext = fileName.toLowerCase().split('.').pop();
    if (!ext || !['docx', 'pdf'].includes(ext)) {
      throw new HttpsError('invalid-argument', 'Only .docx and .pdf files are supported.');
    }

    // Download file from Firebase Storage
    const bucket = admin.storage().bucket();
    const file = bucket.file(storagePath);

    const [exists] = await file.exists();
    if (!exists) {
      throw new HttpsError('not-found', 'File not found in storage.');
    }

    const [buffer] = await file.download();
    console.log(`[processTemplateFile] Downloaded ${fileName} (${buffer.length} bytes)`);

    // Extract text/HTML based on file type
    let extractedHtml = '';
    let extractedText = '';

    if (ext === 'docx') {
      try {
        const result = await mammoth.convertToHtml({ buffer });
        extractedHtml = result.value;
        // Also get raw text for AI analysis
        const textResult = await mammoth.extractRawText({ buffer });
        extractedText = textResult.value;
        console.log(`[processTemplateFile] DOCX extracted: ${extractedHtml.length} chars HTML, ${extractedText.length} chars text`);
      } catch (err) {
        console.error('[processTemplateFile] DOCX extraction error:', err);
        throw new HttpsError('internal', 'Failed to extract text from DOCX file.');
      }
    } else if (ext === 'pdf') {
      try {
        // pdf-parse v2 API: constructor takes { data: buffer }, getText() returns { text, total }
        const parser = new PDFParse({ data: buffer });
        const result = await parser.getText();
        extractedText = result.text || '';
        await parser.destroy();
        // Convert plain text to basic HTML
        extractedHtml = extractedText
          .split('\n\n')
          .map((para: string) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
          .join('\n');
        console.log(`[processTemplateFile] PDF extracted: ${extractedText.length} chars text`);
      } catch (err) {
        console.error('[processTemplateFile] PDF extraction error:', err);
        throw new HttpsError('internal', 'Failed to extract text from PDF file.');
      }
    }

    // Fetch firm data for LLM-agnostic routing
    const firmSnap = await admin.firestore().collection('firms').doc(firmId).get();
    const firmData = firmSnap.data() ?? {};

    // Fetch learning context (corrections, dictionary, few-shot examples)
    const learningCtx = await getLearningContext(firmId);
    const learningPrompt = formatLearningPrompt(learningCtx);

    // Use AI to detect template variables and suggest mappings
    const analysisText = truncateAtWordBoundary(extractedText, 8000);

    const systemPrompt = `You are an expert legal document analyst specializing in estate planning templates.

Analyze the following document text extracted from a ${ext.toUpperCase()} file. Your job is to identify EVERY piece of client-specific data that would need to be replaced when using this document as a template for a different client.

DETECTION STRATEGIES (use ALL of these):

1. **Explicit Placeholders** — formatted as fill-in fields:
   - Handlebars variables: {{variableName}} or {{path.to.field}}
   - Bracket placeholders: [CLIENT NAME], [DATE], [ADDRESS]
   - Underline fill-ins: _______________ (blank lines)
   - ALL-CAPS placeholders: FULL LEGAL NAME, CLIENT ADDRESS
   - Angle-bracket placeholders: <name>, <date>
   - Word merge fields: «FieldName»

2. **Contextual / Semantic Detection** (CRITICAL — most attorney templates are filled-in examples):
   - **Repeated proper names**: If a specific person's name (e.g., "John A. Smith") appears multiple times throughout the document, it is almost certainly the client's name used as sample data. Detect it.
   - **Legal preamble patterns**: Phrases like "I, [Full Name], residing at [Address], County of [County], State of [State]" — even when filled with real values like "I, Jane Doe, residing at 456 Oak Avenue" — should be detected. The name, address, county, and state are all template variables.
   - **Named roles**: People named as executor, trustee, agent, guardian, beneficiary, witness, etc. These are all client-specific data, even if written as real names like "my son, Michael Smith."
   - **Dates**: Specific dates like "March 15, 2024" or "03/15/2024" in the document header, execution lines, or signature blocks are template variables.
   - **Addresses**: Full street addresses, cities, ZIP codes that appear in the document body (not in statutory citations) are client data.
   - **Financial amounts**: Specific dollar amounts in bequests, trust funding, etc.
   - **Relationship references**: "my wife, [Name]", "my daughter, [Name]" — the names are variables.
   - **Cross-referencing**: If you see "John Smith" in the preamble AND later as "Mr. Smith" or "the Grantor," these all refer to the same template variable (clientFullName).

3. **Structural Detection**:
   - Signature blocks with names, dates, notary sections
   - Witness name fields
   - Acknowledgment/notarization sections with county, state, date blanks

For each detected variable, suggest the best matching questionnaire field from the available fields list. Set "confidence" based on:
- "high": Explicit placeholder OR clear legal context (e.g., name in "I, [Name], hereby declare")
- "medium": Likely sample data based on context (e.g., a name after "appointed [Name] as Executor")
- "low": Could be sample data but uncertain (e.g., appears only once with ambiguous context)

${AVAILABLE_FIELDS}
${learningPrompt}
Respond with a valid JSON object (no markdown fences):
{
  "detectedVariables": [
    {
      "originalText": "the exact text found in the document",
      "suggestedVariable": "the Handlebars variable path to use (e.g., personalInfo.firstName)",
      "fieldLabel": "human-readable label (e.g., Client First Name)",
      "confidence": "high" | "medium" | "low",
      "context": "brief context of where this appears in the document"
    }
  ],
  "suggestedDocType": "one of: will, pourOverWill, trust, poa, livingWill, deed, affidavitOfConsideration, gitRep3, estatePlanSummary, actionSteps",
  "documentSummary": "one paragraph summary of what this template is for"
}`;

    const userPrompt = `Analyze this document and detect all template variables/placeholders:\n\n${analysisText}`;

    let detectedVariables: {
      originalText: string;
      suggestedVariable: string;
      fieldLabel: string;
      confidence: string;
      context: string;
    }[] = [];
    let suggestedDocType = '';
    let documentSummary = '';

    try {
      const raw = await callAI(systemPrompt, userPrompt, firmData, {
        temperature: 0.1,
        maxTokens: 4096,
        jsonMode: true,
      });

      const parsed = parseAIJson<{
        detectedVariables: typeof detectedVariables;
        suggestedDocType: string;
        documentSummary: string;
      }>(raw);

      detectedVariables = parsed.detectedVariables ?? [];
      suggestedDocType = parsed.suggestedDocType ?? '';
      documentSummary = parsed.documentSummary ?? '';
    } catch (err) {
      console.error('[processTemplateFile] AI analysis error:', err);
      // Continue without AI analysis — still return the extracted content
    }

    return {
      success: true,
      extractedHtml,
      extractedText: truncateAtWordBoundary(extractedText, 5000),
      detectedVariables,
      suggestedDocType,
      documentSummary,
      fileName,
      fileType: ext,
      learningStats: learningCtx.stats,
    };
  },
);

// ---------------------------------------------------------------------------
// Record user corrections to AI-suggested variable mappings
// ---------------------------------------------------------------------------

export const recordTemplateCorrection = onCall(
  { region: 'us-east1', memory: '256MiB' },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, corrections, templateName, docType } = request.data as {
      firmId: string;
      corrections: {
        originalText: string;
        aiSuggestedVariable: string;
        userCorrectedVariable: string;
      }[];
      templateName: string;
      docType: string;
    };

    if (!firmId || !corrections?.length) {
      throw new HttpsError('invalid-argument', 'firmId and corrections are required.');
    }

    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can record corrections.');
    }

    for (const correction of corrections) {
      await recordCorrection(firmId, {
        ...correction,
        docType: docType ?? 'unknown',
        templateName: templateName ?? 'Untitled',
      });
    }

    console.log(`[recordTemplateCorrection] Recorded ${corrections.length} corrections for firm ${firmId}`);
    return { success: true, recorded: corrections.length };
  },
);

// ---------------------------------------------------------------------------
// Confirm variables after saving a template (builds the learning data)
// ---------------------------------------------------------------------------

export const confirmTemplateVariables = onCall(
  { region: 'us-east1', memory: '256MiB' },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, templateName, docType, variables } = request.data as {
      firmId: string;
      templateName: string;
      docType: string;
      variables: {
        originalText: string;
        confirmedVariable: string;
        fieldLabel: string;
      }[];
    };

    if (!firmId || !variables?.length) {
      throw new HttpsError('invalid-argument', 'firmId and variables are required.');
    }

    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can confirm variables.');
    }

    await recordConfirmedVariables(firmId, templateName, docType, variables);

    console.log(`[confirmTemplateVariables] Confirmed ${variables.length} variables for "${templateName}"`);
    return { success: true, confirmed: variables.length };
  },
);
