/**
 * functions/src/process-template-file.ts
 *
 * Cloud Function to process uploaded .docx and .pdf template files.
 * Downloads the file from Firebase Storage, extracts text/HTML,
 * and uses AI to smart-detect template variables and map them to
 * questionnaire fields.
 */

import { onCall, HttpsError } from 'firebase-functions/v2/https';
import * as admin from 'firebase-admin';
import mammoth from 'mammoth';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pdfParse = require('pdf-parse');
import { callAI, parseAIJson } from './ai-client';

// ---------------------------------------------------------------------------
// Available questionnaire fields (for AI context)
// ---------------------------------------------------------------------------

const AVAILABLE_FIELDS = `
AVAILABLE QUESTIONNAIRE FIELDS (dot-path notation):

personalInfo.firstName, personalInfo.middleName, personalInfo.lastName, personalInfo.suffix
personalInfo.dob, personalInfo.ssnLast4, personalInfo.address, personalInfo.city
personalInfo.state, personalInfo.zip, personalInfo.county, personalInfo.email
personalInfo.phone, personalInfo.maritalStatus, personalInfo.citizenship
personalInfo.occupation, personalInfo.employer

spouseInfo.firstName, spouseInfo.middleName, spouseInfo.lastName
spouseInfo.dob, spouseInfo.email, spouseInfo.phone
spouseInfo.address, spouseInfo.city, spouseInfo.state, spouseInfo.zip

children[] — array of: { name, dob, isMinor, relationship, specialNeeds, guardian, alternateGuardian }

fiduciaries.executor.primary.name, fiduciaries.executor.primary.relationship, fiduciaries.executor.primary.address
fiduciaries.executor.alternate.name, fiduciaries.executor.alternate.relationship
fiduciaries.executor.successor.name
fiduciaries.executor.bondRequired, fiduciaries.executor.compensation

fiduciaries.trustee.primary.name, fiduciaries.trustee.primary.relationship
fiduciaries.trustee.alternate.name, fiduciaries.trustee.successor.name

fiduciaries.powerOfAttorney.agent.name, fiduciaries.powerOfAttorney.agent.relationship
fiduciaries.powerOfAttorney.agent.address, fiduciaries.powerOfAttorney.agent.city, fiduciaries.powerOfAttorney.agent.state, fiduciaries.powerOfAttorney.agent.zip
fiduciaries.powerOfAttorney.alternateAgent.name, fiduciaries.powerOfAttorney.alternateAgent.relationship
fiduciaries.powerOfAttorney.effectiveDate, fiduciaries.powerOfAttorney.giftingAuthority
fiduciaries.powerOfAttorney.powers[]

fiduciaries.healthcareProxy.primary.name, fiduciaries.healthcareProxy.primary.relationship
fiduciaries.healthcareProxy.alternate.name
fiduciaries.healthcareProxy.lifeSupport, fiduciaries.healthcareProxy.nutrition
fiduciaries.healthcareProxy.painManagement, fiduciaries.healthcareProxy.organDonation

fiduciaries.guardian.primary.name, fiduciaries.guardian.alternate.name

distribution.residualDistributions[] — { recipient, recipientRelationship, percentage, perStirpes, alternateRecipient }
distribution.specificBequests[] — { description, recipient, condition, alternateRecipient }
distribution.charitableBequests[] — { organizationName, ein, amount, percentage, purpose }
distribution.trustName, distribution.pourOverToTrust, distribution.noContestClause
distribution.spendthriftProvision, distribution.survivorshipPeriod

assets.realEstate[] — { address, type, currentValue, ownershipType, mortgageBalance }
assets.investments[] — { institution, accountType, estimatedValue }
assets.insurance[] — { company, policyType, deathBenefit, beneficiary }
assets.digitalAssets[] — { name, type }

specialConsiderations.hasSpecialNeedsChild, specialConsiderations.specialNeedsDetails
specialConsiderations.hasPetProvision, specialConsiderations.petDetails, specialConsiderations.petCaretaker

COMPUTED FIELDS (generated by system, not from questionnaire):
clientFullName, spouseFullName, hasSpouse, hasMinorChildren, hasSpecialNeedsChild
childCount, minorChildren[], adultChildren[], propertyCount
propertiesForTrust[], estimatedTotalAssets, primaryTrustName
todayFormatted, todayISO, packageType, packageLabel
`;

// ---------------------------------------------------------------------------
// Cloud Function
// ---------------------------------------------------------------------------

export const processTemplateFile = onCall(
  { region: 'us-east1', memory: '1GiB', timeoutSeconds: 120 },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, storagePath, fileName } = request.data as {
      firmId: string;
      storagePath: string;
      fileName: string;
    };

    if (!firmId || !storagePath || !fileName) {
      throw new HttpsError('invalid-argument', 'firmId, storagePath, and fileName are required.');
    }

    // Validate role
    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can process templates.');
    }

    const ext = fileName.toLowerCase().split('.').pop();
    if (!ext || !['docx', 'pdf'].includes(ext)) {
      throw new HttpsError('invalid-argument', 'Only .docx and .pdf files are supported.');
    }

    // Download file from Firebase Storage
    const bucket = admin.storage().bucket();
    const file = bucket.file(storagePath);

    const [exists] = await file.exists();
    if (!exists) {
      throw new HttpsError('not-found', 'File not found in storage.');
    }

    const [buffer] = await file.download();
    console.log(`[processTemplateFile] Downloaded ${fileName} (${buffer.length} bytes)`);

    // Extract text/HTML based on file type
    let extractedHtml = '';
    let extractedText = '';

    if (ext === 'docx') {
      try {
        const result = await mammoth.convertToHtml({ buffer });
        extractedHtml = result.value;
        // Also get raw text for AI analysis
        const textResult = await mammoth.extractRawText({ buffer });
        extractedText = textResult.value;
        console.log(`[processTemplateFile] DOCX extracted: ${extractedHtml.length} chars HTML, ${extractedText.length} chars text`);
      } catch (err) {
        console.error('[processTemplateFile] DOCX extraction error:', err);
        throw new HttpsError('internal', 'Failed to extract text from DOCX file.');
      }
    } else if (ext === 'pdf') {
      try {
        const pdfData = await pdfParse(buffer);
        extractedText = pdfData.text;
        // Convert plain text to basic HTML
        extractedHtml = extractedText
          .split('\n\n')
          .map((para: string) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
          .join('\n');
        console.log(`[processTemplateFile] PDF extracted: ${extractedText.length} chars text`);
      } catch (err) {
        console.error('[processTemplateFile] PDF extraction error:', err);
        throw new HttpsError('internal', 'Failed to extract text from PDF file.');
      }
    }

    // Use AI to detect template variables and suggest mappings
    const analysisText = extractedText.slice(0, 8000);

    const systemPrompt = `You are an expert legal document analyst specializing in estate planning templates.

Analyze the following document text extracted from a ${ext.toUpperCase()} file and identify ALL placeholders, fill-in fields, and variable locations that would need to be replaced with client-specific data when generating a document from this template.

Look for these patterns:
1. Handlebars variables: {{variableName}} or {{path.to.field}}
2. Bracket placeholders: [CLIENT NAME], [DATE], [ADDRESS], etc.
3. Underline fill-ins: _______________ (blank lines for writing in data)
4. ALL-CAPS placeholders: FULL LEGAL NAME, CLIENT ADDRESS
5. Angle-bracket placeholders: <name>, <date>
6. Word merge fields: «FieldName»
7. Any other obvious placeholder patterns

For each detected variable, suggest the best matching questionnaire field from the available fields list.

${AVAILABLE_FIELDS}

Respond with a valid JSON object (no markdown fences):
{
  "detectedVariables": [
    {
      "originalText": "the exact text found in the document",
      "suggestedVariable": "the Handlebars variable path to use (e.g., personalInfo.firstName)",
      "fieldLabel": "human-readable label (e.g., Client First Name)",
      "confidence": "high" | "medium" | "low",
      "context": "brief context of where this appears in the document"
    }
  ],
  "suggestedDocType": "one of: will, pourOverWill, trust, poa, livingWill, deed, affidavitOfConsideration, gitRep3, estatePlanSummary, actionSteps",
  "documentSummary": "one paragraph summary of what this template is for"
}`;

    const userPrompt = `Analyze this document and detect all template variables/placeholders:\n\n${analysisText}`;

    let detectedVariables: {
      originalText: string;
      suggestedVariable: string;
      fieldLabel: string;
      confidence: string;
      context: string;
    }[] = [];
    let suggestedDocType = '';
    let documentSummary = '';

    try {
      const raw = await callAI(systemPrompt, userPrompt, {}, {
        model: 'gpt-4.1-mini',
        temperature: 0.1,
        maxTokens: 4096,
        jsonMode: true,
      });

      const parsed = parseAIJson<{
        detectedVariables: typeof detectedVariables;
        suggestedDocType: string;
        documentSummary: string;
      }>(raw);

      detectedVariables = parsed.detectedVariables ?? [];
      suggestedDocType = parsed.suggestedDocType ?? '';
      documentSummary = parsed.documentSummary ?? '';
    } catch (err) {
      console.error('[processTemplateFile] AI analysis error:', err);
      // Continue without AI analysis — still return the extracted content
    }

    return {
      success: true,
      extractedHtml,
      extractedText: extractedText.slice(0, 5000), // Preview only
      detectedVariables,
      suggestedDocType,
      documentSummary,
      fileName,
      fileType: ext,
    };
  },
);
