/**
 * functions/src/process-template-file.ts
 *
 * Cloud Function to process uploaded .docx and .pdf template files.
 * Downloads the file from Firebase Storage, extracts text/HTML,
 * and uses AI to smart-detect template variables and map them to
 * questionnaire fields.
 */

import { onCall, HttpsError } from 'firebase-functions/v2/https';
import * as admin from 'firebase-admin';
import mammoth from 'mammoth';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PDFParse } = require('pdf-parse');
import { callAI, parseAIJson } from './ai-client';
import { getLearningContext, formatLearningPrompt, recordCorrection, recordConfirmedVariables } from './template-learning';

// ---------------------------------------------------------------------------
// Helper: truncate text at a word boundary
// ---------------------------------------------------------------------------
function truncateAtWordBoundary(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  const truncated = text.slice(0, maxLen);
  const lastSpace = truncated.lastIndexOf(' ');
  return lastSpace > maxLen * 0.8 ? truncated.slice(0, lastSpace) + '…' : truncated + '…';
}

// ---------------------------------------------------------------------------
// Available questionnaire fields (for AI context)
// ---------------------------------------------------------------------------

const AVAILABLE_FIELDS = `
AVAILABLE QUESTIONNAIRE FIELDS (dot-path notation):

personalInfo.firstName, personalInfo.middleName, personalInfo.lastName, personalInfo.suffix
personalInfo.dob, personalInfo.ssnLast4, personalInfo.address, personalInfo.city
personalInfo.state, personalInfo.zip, personalInfo.county, personalInfo.email
personalInfo.phone, personalInfo.maritalStatus, personalInfo.citizenship
personalInfo.occupation, personalInfo.employer

spouseInfo.firstName, spouseInfo.middleName, spouseInfo.lastName
spouseInfo.dob, spouseInfo.email, spouseInfo.phone
spouseInfo.address, spouseInfo.city, spouseInfo.state, spouseInfo.zip

children[] — array of: { name, dob, isMinor, relationship, specialNeeds, guardian, alternateGuardian }

fiduciaries.executor.primary.name, fiduciaries.executor.primary.relationship, fiduciaries.executor.primary.address
fiduciaries.executor.alternate.name, fiduciaries.executor.alternate.relationship
fiduciaries.executor.successor.name
fiduciaries.executor.bondRequired, fiduciaries.executor.compensation

fiduciaries.trustee.primary.name, fiduciaries.trustee.primary.relationship
fiduciaries.trustee.alternate.name, fiduciaries.trustee.successor.name

fiduciaries.powerOfAttorney.agent.name, fiduciaries.powerOfAttorney.agent.relationship
fiduciaries.powerOfAttorney.agent.address, fiduciaries.powerOfAttorney.agent.city, fiduciaries.powerOfAttorney.agent.state, fiduciaries.powerOfAttorney.agent.zip
fiduciaries.powerOfAttorney.alternateAgent.name, fiduciaries.powerOfAttorney.alternateAgent.relationship
fiduciaries.powerOfAttorney.effectiveDate, fiduciaries.powerOfAttorney.giftingAuthority
fiduciaries.powerOfAttorney.powers[]

fiduciaries.healthcareProxy.primary.name, fiduciaries.healthcareProxy.primary.relationship
fiduciaries.healthcareProxy.alternate.name
fiduciaries.healthcareProxy.lifeSupport, fiduciaries.healthcareProxy.nutrition
fiduciaries.healthcareProxy.painManagement, fiduciaries.healthcareProxy.organDonation

fiduciaries.guardian.primary.name, fiduciaries.guardian.alternate.name

distribution.residualDistributions[] — { recipient, recipientRelationship, percentage, perStirpes, alternateRecipient }
distribution.specificBequests[] — { description, recipient, condition, alternateRecipient }
distribution.charitableBequests[] — { organizationName, ein, amount, percentage, purpose }
distribution.trustName, distribution.pourOverToTrust, distribution.noContestClause
distribution.spendthriftProvision, distribution.survivorshipPeriod

assets.realEstate[] — { address, type, currentValue, ownershipType, mortgageBalance }
assets.investments[] — { institution, accountType, estimatedValue }
assets.insurance[] — { company, policyType, deathBenefit, beneficiary }
assets.digitalAssets[] — { name, type }

specialConsiderations.hasSpecialNeedsChild, specialConsiderations.specialNeedsDetails
specialConsiderations.hasPetProvision, specialConsiderations.petDetails, specialConsiderations.petCaretaker

COMPUTED FIELDS (generated by system, not from questionnaire):
clientFullName, spouseFullName, hasSpouse, hasMinorChildren, hasSpecialNeedsChild
childCount, minorChildren[], adultChildren[], propertyCount
propertiesForTrust[], estimatedTotalAssets, primaryTrustName
todayFormatted, todayISO, packageType, packageLabel

RELATIONSHIP TITLE FIELDS (auto-derived from questionnaire data):
spouseTitle — "husband", "wife", or "partner" (derived from client gender + marital status)
clientTitle — the client's own relationship descriptor (reverse of spouseTitle)
executorTitle — relationship descriptor for executor (from fiduciaries.executor.primary.relationship)
alternateExecutorTitle — relationship descriptor for alternate executor
trusteeTitle — relationship descriptor for trustee
poaAgentTitle — relationship descriptor for POA agent
healthcareRepTitle — relationship descriptor for healthcare rep
guardianTitle — relationship descriptor for guardian
clientPronouns.subject / .object / .possessive — he/him/his or she/her/her
spousePronouns.subject / .object / .possessive — he/him/his or she/her/her
childrenWithTitles[] — same as children[] but each child also has a "childTitle" field = "son"/"daughter"/"stepson"/"stepdaughter"

CRITICAL MAPPING RULES — RELATIONSHIP WORDS vs NAMES:
- "my husband", "my wife", "my partner" → map to spouseTitle (NOT spouseFullName)
- "my son", "my daughter", "my stepson", "my stepdaughter" → map to the child's childTitle (NOT to a name field)
- "my children" (collective reference) → do NOT map; leave as literal text
- "he", "him", "his", "she", "her" referring to the client → map to clientPronouns.subject / .object / .possessive
- "he", "him", "his", "she", "her" referring to the spouse → map to spousePronouns.subject / .object / .possessive
- Only actual NAMES (e.g., "John Smith", "Jane Doe") should map to name fields like clientFullName, spouseFullName, children[0].name
- Phrases like "my husband, Sean Byrnes" contain TWO variables: "my husband" → spouseTitle, "Sean Byrnes" → spouseFullName
`;

const AVAILABLE_TAGS = `
AVAILABLE TEMPLATE TAGS — select ALL that apply based on document content:

Document Type tags:
- "standard-will" — a standard last will and testament
- "pour-over-will" — a pour-over will directing assets into a trust
- "simple-will" — a simple/basic will
- "revocable-trust" — a revocable living trust
- "irrevocable-trust" — an irrevocable trust
- "special-needs-trust" — a special needs trust
- "financial-poa" — a financial/durable power of attorney
- "healthcare-poa" — a healthcare power of attorney / healthcare proxy
- "living-will" — a living will or advance directive
- "guardianship" — a guardianship designation

Client tags:
- "male-client" — the primary client/testator/grantor is male
- "female-client" — the primary client/testator/grantor is female
- "husband" — the client is a husband
- "wife" — the client is a wife
- "married" — the client is married (spouse referenced)
- "single" — the client is single/unmarried
- "has-children" — children are referenced in the document
- "has-minor-children" — minor children or guardianship provisions are present

Role tags:
- "male-executor" — the named executor is male
- "female-executor" — the named executor is female
- "male-trustee" — the named trustee is male
- "female-trustee" — the named trustee is female
- "corporate-trustee" — a corporate/institutional trustee is named

Jurisdiction tags:
- "nj" — New Jersey law referenced or NJ-specific provisions
- "ny" — New York law referenced or NY-specific provisions
- "pa" — Pennsylvania law referenced or PA-specific provisions
`;

// ---------------------------------------------------------------------------
// Cloud Function
// ---------------------------------------------------------------------------

export const processTemplateFile = onCall(
  { region: 'us-east1', memory: '1GiB', timeoutSeconds: 240 },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, storagePath, fileName } = request.data as {
      firmId: string;
      storagePath: string;
      fileName: string;
    };

    if (!firmId || !storagePath || !fileName) {
      throw new HttpsError('invalid-argument', 'firmId, storagePath, and fileName are required.');
    }

    // Validate role
    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can process templates.');
    }

    const ext = fileName.toLowerCase().split('.').pop();
    if (!ext || !['docx', 'pdf'].includes(ext)) {
      throw new HttpsError('invalid-argument', 'Only .docx and .pdf files are supported.');
    }

    // Download file from Firebase Storage
    const bucket = admin.storage().bucket();
    const file = bucket.file(storagePath);

    const [exists] = await file.exists();
    if (!exists) {
      throw new HttpsError('not-found', 'File not found in storage.');
    }

    const [buffer] = await file.download();
    console.log(`[processTemplateFile] Downloaded ${fileName} (${buffer.length} bytes)`);

    // Extract text/HTML based on file type
    let extractedHtml = '';
    let extractedText = '';

    if (ext === 'docx') {
      try {
        const result = await mammoth.convertToHtml({ buffer });
        extractedHtml = result.value;
        // Also get raw text for AI analysis
        const textResult = await mammoth.extractRawText({ buffer });
        extractedText = textResult.value;
        console.log(`[processTemplateFile] DOCX extracted: ${extractedHtml.length} chars HTML, ${extractedText.length} chars text`);
      } catch (err) {
        console.error('[processTemplateFile] DOCX extraction error:', err);
        throw new HttpsError('internal', 'Failed to extract text from DOCX file.');
      }
    } else if (ext === 'pdf') {
      try {
        // pdf-parse v2 API: constructor takes { data: buffer }, getText() returns { text, total }
        const parser = new PDFParse({ data: buffer });
        const result = await parser.getText();
        extractedText = result.text || '';
        await parser.destroy();
        // Convert plain text to basic HTML
        extractedHtml = extractedText
          .split('\n\n')
          .map((para: string) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
          .join('\n');
        console.log(`[processTemplateFile] PDF extracted: ${extractedText.length} chars text`);
      } catch (err) {
        console.error('[processTemplateFile] PDF extraction error:', err);
        throw new HttpsError('internal', 'Failed to extract text from PDF file.');
      }
    }

    // Fetch firm data for LLM-agnostic routing
    const firmSnap = await admin.firestore().collection('firms').doc(firmId).get();
    const firmData = firmSnap.data() ?? {};

    // Fetch learning context (corrections, dictionary, few-shot examples)
    const learningCtx = await getLearningContext(firmId);
    const learningPrompt = formatLearningPrompt(learningCtx);

    // Use AI to detect template variables and suggest mappings
    // -----------------------------------------------------------------------
    // Multi-pass detection: split large documents into overlapping chunks
    // to ensure full coverage (each chunk ≤ 15K chars, 3K overlap)
    // -----------------------------------------------------------------------
    const CHUNK_SIZE = 15000;
    const CHUNK_OVERLAP = 3000;

    const chunks: string[] = [];
    if (extractedText.length <= CHUNK_SIZE) {
      chunks.push(truncateAtWordBoundary(extractedText, CHUNK_SIZE));
    } else {
      let offset = 0;
      while (offset < extractedText.length) {
        const end = Math.min(offset + CHUNK_SIZE, extractedText.length);
        chunks.push(truncateAtWordBoundary(extractedText.slice(offset, end), CHUNK_SIZE));
        if (end >= extractedText.length) break;
        offset += CHUNK_SIZE - CHUNK_OVERLAP;
      }
    }

    console.log(`[processTemplateFile] Analyzing ${chunks.length} chunk(s) (text length: ${extractedText.length} chars)`);

    const systemPrompt = `You are an expert legal document analyst specializing in estate planning templates.

Analyze the following document text extracted from a ${ext.toUpperCase()} file. Your job is to identify EVERY piece of client-specific data that would need to be replaced when using this document as a template for a different client.

DETECTION STRATEGIES (use ALL of these):

1. **Explicit Placeholders** — formatted as fill-in fields:
   - Handlebars variables: {{variableName}} or {{path.to.field}}
   - Bracket placeholders: [CLIENT NAME], [DATE], [ADDRESS]
   - Underline fill-ins: _______________ (blank lines)
   - ALL-CAPS placeholders: FULL LEGAL NAME, CLIENT ADDRESS
   - Angle-bracket placeholders: <name>, <date>
   - Word merge fields: «FieldName»

2. **Contextual / Semantic Detection** (CRITICAL — most attorney templates are filled-in examples):
   - **Repeated proper names**: If a specific person's name (e.g., "John A. Smith") appears multiple times throughout the document, it is almost certainly the client's name used as sample data. Detect it.
   - **Legal preamble patterns**: Phrases like "I, [Full Name], residing at [Address], County of [County], State of [State]" — even when filled with real values like "I, Jane Doe, residing at 456 Oak Avenue" — should be detected. The name, address, county, and state are all template variables.
   - **Named roles**: People named as executor, trustee, agent, guardian, beneficiary, witness, etc. These are all client-specific data, even if written as real names like "my son, Michael Smith."
   - **Dates**: Specific dates like "March 15, 2024" or "03/15/2024" in the document header, execution lines, or signature blocks are template variables.
   - **Addresses**: Full street addresses, cities, ZIP codes that appear in the document body (not in statutory citations) are client data.
   - **Financial amounts**: Specific dollar amounts in bequests, trust funding, etc.
   - **Relationship references**: "my wife, [Name]", "my daughter, [Name]" — the names are variables.
   - **Cross-referencing**: If you see "John Smith" in the preamble AND later as "Mr. Smith" or "the Grantor," these all refer to the same template variable (clientFullName).

3. **Structural Detection**:
   - Signature blocks with names, dates, notary sections
   - Witness name fields
   - Acknowledgment/notarization sections with county, state, date blanks

For each detected variable, suggest the best matching questionnaire field from the available fields list. Set "confidence" based on:
- "high": Explicit placeholder OR clear legal context (e.g., name in "I, [Name], hereby declare")
- "medium": Likely sample data based on context (e.g., a name after "appointed [Name] as Executor")
- "low": Could be sample data but uncertain (e.g., appears only once with ambiguous context)

${AVAILABLE_FIELDS}
${AVAILABLE_TAGS}
${learningPrompt}
Respond with a valid JSON object (no markdown fences):
{
  "detectedVariables": [
    {
      "originalText": "the exact text found in the document",
      "suggestedVariable": "the Handlebars variable path to use (e.g., personalInfo.firstName)",
      "fieldLabel": "human-readable label (e.g., Client First Name)",
      "confidence": "high" | "medium" | "low",
      "context": "brief context of where this appears in the document"
    }
  ],
  "suggestedDocType": "one of: will, pourOverWill, trust, poa, livingWill, deed, affidavitOfConsideration, gitRep3, estatePlanSummary, actionSteps",
  "suggestedTags": ["array of tag values from the AVAILABLE TEMPLATE TAGS list above that match this document"],
  "documentSummary": "one paragraph summary of what this template is for"
}`;

    let detectedVariables: {
      originalText: string;
      suggestedVariable: string;
      fieldLabel: string;
      confidence: string;
      context: string;
    }[] = [];
    let suggestedDocType = '';
    let suggestedTags: string[] = [];
    let documentSummary = '';

    const confidenceRank: Record<string, number> = { high: 3, medium: 2, low: 1 };

    try {
      // Process each chunk and merge results
      for (let ci = 0; ci < chunks.length; ci++) {
        const chunkLabel = chunks.length > 1 ? ` (chunk ${ci + 1}/${chunks.length})` : '';
        const userPrompt = `Analyze this document${chunkLabel} and detect all template variables/placeholders:\n\n${chunks[ci]}`;

        const raw = await callAI(systemPrompt, userPrompt, firmData, {
          temperature: 0,
          maxTokens: 4096,
          jsonMode: true,
        });

        const parsed = parseAIJson<{
          detectedVariables: typeof detectedVariables;
          suggestedDocType: string;
          suggestedTags: string[];
          documentSummary: string;
        }>(raw);

        const chunkVars = parsed.detectedVariables ?? [];

        if (ci === 0) {
          // First chunk — take docType and summary from it
          suggestedDocType = parsed.suggestedDocType ?? '';
          suggestedTags = parsed.suggestedTags ?? [];
          documentSummary = parsed.documentSummary ?? '';
          detectedVariables = chunkVars;
        } else {
          // Subsequent chunks — merge variables, deduplicate by originalText
          for (const newVar of chunkVars) {
            const existingIdx = detectedVariables.findIndex(
              (v) => v.originalText.toLowerCase() === newVar.originalText.toLowerCase(),
            );
            if (existingIdx >= 0) {
              // Keep the higher-confidence version
              const existing = detectedVariables[existingIdx];
              const existingRank = confidenceRank[existing.confidence] ?? 0;
              const newRank = confidenceRank[newVar.confidence] ?? 0;
              if (newRank > existingRank) {
                detectedVariables[existingIdx] = newVar;
              }
            } else {
              detectedVariables.push(newVar);
            }
          }
        }

        if (chunks.length > 1) {
          console.log(`[processTemplateFile] Chunk ${ci + 1}/${chunks.length}: detected ${chunkVars.length} variables (total unique: ${detectedVariables.length})`);
        }
      }
    } catch (err) {
      console.error('[processTemplateFile] AI analysis error:', err);
      // Continue without AI analysis — still return the extracted content
    }

    // -----------------------------------------------------------------------
    // Step 2: Templatize content — replace detected literal text with
    // Handlebars variable tags in the extracted HTML
    // -----------------------------------------------------------------------
    let templatizedHtml = extractedHtml;

    if (detectedVariables.length > 0) {
      // Sort by originalText length descending so longer matches are replaced
      // first (prevents partial replacements, e.g., "Jack" inside "Jack Byrnes")
      const sorted = [...detectedVariables].sort(
        (a, b) => b.originalText.length - a.originalText.length,
      );

      for (const v of sorted) {
        if (!v.originalText || !v.suggestedVariable) continue;
        // Skip very short matches (< 2 chars) to avoid replacing "I", "a", etc.
        if (v.originalText.length < 2) continue;

        const tag = `{{${v.suggestedVariable}}}`;
        // Use a regex for case-sensitive whole-word-ish matching
        // Escape special regex characters in the match text
        const escaped = v.originalText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(escaped, 'g');
        templatizedHtml = templatizedHtml.replace(regex, tag);
      }

      console.log(`[processTemplateFile] Templatized content: replaced ${sorted.length} variable occurrences`);
    }

    // -----------------------------------------------------------------------
    // Step 3: AI loop detection — detect repeating child-reference patterns
    // and convert indexed children (children[0], children[1], ...) into
    // {{#each childrenWithTitles}} loops
    // -----------------------------------------------------------------------
    const hasIndexedChildren = detectedVariables.some(
      (v) => /children\[\d+\]/.test(v.suggestedVariable),
    );

    if (hasIndexedChildren) {
      try {
        const loopPrompt = `You are a Handlebars template expert. The following HTML template has been partially converted — it contains indexed child references like {{children[0].name}}, {{children[1].name}}, {{childrenWithTitles[0].childTitle}}, etc.

Your job: find the REPEATING sections that reference individual children by index (children[0], children[1], children[2], childrenWithTitles[0], etc.) and convert them into a single {{#each childrenWithTitles}} loop block.

RULES:
1. Identify THE SMALLEST repeating unit — the clause or paragraph that repeats for each child.
2. Replace ALL indexed instances of that clause with a SINGLE {{#each childrenWithTitles}} block.
3. Inside the block, use {{this.childTitle}} for "son"/"daughter", {{this.name}} for the child's name, and {{this.dob}}, {{this.relationship}}, etc. for other child fields.
4. Use {{@index}}, {{@first}}, {{@last}} for ordinal logic if needed (e.g., "and" before the last child).
5. Do NOT touch sections that reference children collectively (e.g., "my children") — leave those as literal text.
6. Do NOT modify any other part of the template — only the repeating child sections.
7. Preserve all HTML structure and formatting.
8. If children references are NOT repeating (e.g., just one child mentioned), leave them as indexed references.

Return ONLY the modified HTML (no JSON wrapper, no markdown fences, no explanation).`;

        const loopResult = await callAI(loopPrompt, templatizedHtml.slice(0, 15000), firmData, {
          temperature: 0.05,
          maxTokens: 15000,
        });

        // Validate the AI returned something reasonable
        if (loopResult && loopResult.trim().length > 100 && loopResult.includes('{{#each')) {
          templatizedHtml = loopResult;
          console.log('[processTemplateFile] AI loop detection: converted indexed children to {{#each}} block');
        } else {
          console.log('[processTemplateFile] AI loop detection: no repeating pattern found or AI returned unchanged content');
        }
      } catch (err) {
        console.error('[processTemplateFile] AI loop detection error (non-fatal):', err);
        // Continue with the templatized content without loop conversion
      }
    }

    return {
      success: true,
      extractedHtml: templatizedHtml,
      extractedText: truncateAtWordBoundary(extractedText, 5000),
      detectedVariables,
      suggestedDocType,
      suggestedTags,
      documentSummary,
      fileName,
      fileType: ext,
      learningStats: learningCtx.stats,
    };
  },
);

// ---------------------------------------------------------------------------
// Record user corrections to AI-suggested variable mappings
// ---------------------------------------------------------------------------

export const recordTemplateCorrection = onCall(
  { region: 'us-east1', memory: '256MiB' },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, corrections, templateName, docType } = request.data as {
      firmId: string;
      corrections: {
        originalText: string;
        aiSuggestedVariable: string;
        userCorrectedVariable: string;
      }[];
      templateName: string;
      docType: string;
    };

    if (!firmId || !corrections?.length) {
      throw new HttpsError('invalid-argument', 'firmId and corrections are required.');
    }

    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can record corrections.');
    }

    for (const correction of corrections) {
      await recordCorrection(firmId, {
        ...correction,
        docType: docType ?? 'unknown',
        templateName: templateName ?? 'Untitled',
      });
    }

    console.log(`[recordTemplateCorrection] Recorded ${corrections.length} corrections for firm ${firmId}`);
    return { success: true, recorded: corrections.length };
  },
);

// ---------------------------------------------------------------------------
// Confirm variables after saving a template (builds the learning data)
// ---------------------------------------------------------------------------

export const confirmTemplateVariables = onCall(
  { region: 'us-east1', memory: '256MiB' },
  async (request) => {
    if (!request.auth) throw new HttpsError('unauthenticated', 'Sign in required.');

    const { firmId, templateName, docType, variables } = request.data as {
      firmId: string;
      templateName: string;
      docType: string;
      variables: {
        originalText: string;
        confirmedVariable: string;
        fieldLabel: string;
      }[];
    };

    if (!firmId || !variables?.length) {
      throw new HttpsError('invalid-argument', 'firmId and variables are required.');
    }

    const role = request.auth.token.role as string | undefined;
    if (!role || !['admin', 'attorney'].includes(role)) {
      throw new HttpsError('permission-denied', 'Only attorneys and administrators can confirm variables.');
    }

    await recordConfirmedVariables(firmId, templateName, docType, variables);

    console.log(`[confirmTemplateVariables] Confirmed ${variables.length} variables for "${templateName}"`);
    return { success: true, confirmed: variables.length };
  },
);
