import type {
  L9ABeneficiaryRow,
  L9AFormData,
  L9ARealProperty,
  Matter,
  ReviewCheckpoint,
  TaxClass,
} from '../types';
import { classifyBeneficiary } from '../engine';
import { DISCLAIMER } from './disclaimer';
import { UnsupportedMatterError, FormPreconditionError } from './errors';

const MAILING_ADDRESS =
  'NJ Division of Taxation, Transfer Inheritance Tax, PO Box 249, Trenton, NJ 08695-0249';

// Attachments common to L-9 and L-9(A).
const COMMON_ATTACHMENTS = [
  "Copy of the decedent's will, codicils and related writings, and any trust agreements",
  'Copy of the deed for each property listed on the form',
  "Copy of the executor's or administrator's certificate (letters testamentary or of administration)",
  "Copy of the decedent's death certificate",
];

// L-9(A) (pre-2018 deaths) requires two additional attachments per the official instructions.
const L9A_ADDITIONAL_ATTACHMENTS = [
  "Copy of the decedent's last full-year federal income tax return (include Schedules A, B, and D, or a statement that none was filed)",
  'Copy of any existing appraisals or current contracts of sale',
];

const FILING_NOTE =
  'This affidavit is NOT itself a tax waiver and carries no filing fee. Do not file it with ' +
  'the County Clerk — mail it to the Division of Taxation, which issues the waiver releasing ' +
  'the lien. The form may be used ONLY when all beneficiaries are Class A and no NJ ' +
  'Inheritance or Estate Tax is due; otherwise a full Inheritance/Estate Tax return is required.';

const CITATION =
  'N.J.S.A. 54:35-5 (estate tax lien); N.J.A.C. 18:26-11.1 (lien discharge); ' +
  'NJ Form L-9 / L-9(A) (nj.gov/treasury/taxation/pdf/other_forms/inheritance/itl9a.pdf)';

/** Resolves a beneficiary's operative tax class (honoring any attorney override). */
function beneficiaryClass(b: Matter['beneficiaries'][number]): TaxClass {
  return b.taxClassOverride?.taxClass ?? classifyBeneficiary(b.relationship);
}

/**
 * Builds the data model for the NJ Affidavit Requesting Real Property Tax Waiver
 * (Form L-9(A) for deaths before 2018-01-01; Form L-9 on/after). It releases the
 * Inheritance/Estate Tax lien on real property (N.J.S.A. 54:35-5; N.J.A.C. 18:26-11.1)
 * so property can transfer without a full return.
 *
 * Per the official form, this affidavit may be used ONLY when:
 *   - the decedent owned NJ real property (there is a lien to release);
 *   - every beneficiary is Class A (no asset ≥ $500 passes to a non-Class-A beneficiary); and
 *   - no NJ Inheritance Tax or Estate Tax is due.
 * The builder enforces all three from the approved snapshot and throws otherwise, so an
 * L-9 is never produced for an estate that actually requires a return.
 *
 * Throws if the checkpoint is not approved or belongs to a different matter.
 */
export function buildL9AFormData(
  matter: Matter,
  approvedCheckpoint: ReviewCheckpoint,
): L9AFormData {
  if (approvedCheckpoint.status !== 'approved') {
    throw new FormPreconditionError('Cannot generate L-9 form data without an approved review checkpoint.');
  }

  if (approvedCheckpoint.matterId !== matter.matterId) {
    throw new Error(
      `Checkpoint matterId '${approvedCheckpoint.matterId}' does not match ` +
      `matter matterId '${matter.matterId}'. ` +
      'Cannot generate L-9 form data from a checkpoint belonging to a different matter.',
    );
  }

  // L-9 / L-9(A) are RESIDENT decedent forms; nonresident decedents use Form L-9 NR
  // (not generated by this tool). Route them away rather than emit the wrong affidavit.
  if (matter.decedent.isNJResident === false) {
    throw new UnsupportedMatterError(
      'Cannot generate L-9: the decedent was a nonresident. Nonresident decedents use ' +
      'Form L-9 NR, which this tool does not generate.',
    );
  }

  // L-9(A) (deaths before 2018-01-01) vs L-9 (on/after) — same affidavit, date-split.
  const formDesignation = matter.decedent.dateOfDeath < '2018-01-01' ? 'L-9(A)' : 'L-9';

  // L-9(A) explicitly cannot be used when a trust agreement exists or is created by the
  // will. (For L-9 the trust restriction is conditional, so it is surfaced as a caveat
  // rather than a hard block.)
  if (matter.trustExists && formDesignation === 'L-9(A)') {
    throw new FormPreconditionError(
      'Cannot generate L-9(A): a trust agreement exists or is created by the will. The ' +
      'L-9(A) affidavit cannot be used for trust estates — file a full return.',
    );
  }

  // A claimed "mutually acknowledged child" relationship bars the L-9 / L-9(A) affidavit
  // even though that relationship is otherwise Class A.
  const mutuallyAcknowledged = matter.beneficiaries.find(
    (b) => b.relationship === 'mutually_acknowledged_child',
  );
  if (mutuallyAcknowledged !== undefined) {
    throw new FormPreconditionError(
      'Cannot generate L-9: a mutually acknowledged child relationship is claimed, which ' +
      'the L-9 / L-9(A) affidavit prohibits. File a full return.',
    );
  }

  // Real property whose lien the waiver releases (Schedule A — NJ real property).
  const realProperties: L9ARealProperty[] = matter.beneficiaries.flatMap((b) =>
    b.bequests
      .filter((q) => q.type === 'nj_real_property')
      .map((q) => {
        // Schedule A's columns, where intake captured them. Spread conditionally so a matter
        // without the detail block carries no empty keys into the frozen form data.
        const d = q.realPropertyDetails;
        return {
          description: q.description,
          fairMarketValue: q.fairMarketValue,
          beneficiaryName: `${b.firstName} ${b.lastName}`.trim(),
          ...(d?.county !== undefined ? { county: d.county } : {}),
          ...(d?.streetAddress !== undefined ? { streetAddress: d.streetAddress } : {}),
          ...(d?.lots !== undefined ? { lots: d.lots } : {}),
          ...(d?.block !== undefined ? { block: d.block } : {}),
          ...(d?.municipality !== undefined ? { municipality: d.municipality } : {}),
          ...(d?.ownersAndTitle !== undefined ? { ownersAndTitle: d.ownersAndTitle } : {}),
        };
      }),
  );
  if (realProperties.length === 0) {
    throw new FormPreconditionError(
      'Cannot generate L-9: the estate has no NJ real property (Schedule A is empty). ' +
      'The real property tax waiver applies only to NJ real estate.',
    );
  }

  // Eligibility: no asset ≥ $500 may pass to a beneficiary who is not Class A.
  const beneficiaries: L9ABeneficiaryRow[] = matter.beneficiaries.map((b) => {
    const interestValue = b.bequests.reduce((sum, q) => sum + q.fairMarketValue, 0);
    return {
      fullName: `${b.firstName} ${b.lastName}`.trim(),
      relationship: b.relationship,
      taxClass: beneficiaryClass(b),
      interestValue,
    };
  });
  const disqualifying = beneficiaries.find((b) => b.taxClass !== 'A' && b.interestValue >= 500);
  if (disqualifying !== undefined) {
    throw new FormPreconditionError(
      `Cannot generate L-9: beneficiary '${disqualifying.fullName}' is Class ` +
      `${disqualifying.taxClass} and receives $500 or more. The L-9 affidavit requires all ` +
      'beneficiaries (receiving $500+) to be Class A; this estate must file a full return.',
    );
  }

  // Eligibility: no NJ Inheritance or Estate Tax may be due.
  const snap = approvedCheckpoint.computationSnapshot;
  const mi = snap.matterInputs;
  const inheritanceTax = snap.totalTaxDue + mi.compromiseTax + mi.contingentTax;
  if (inheritanceTax > 0) {
    throw new FormPreconditionError(
      'Cannot generate L-9: NJ Inheritance Tax is due. The L-9 affidavit is only for estates ' +
      'with no Inheritance or Estate Tax; file the IT-R return instead.',
    );
  }
  const est = snap.njEstateTax;
  if (est !== null && (est.filingRequired || (est.taxDue ?? 0) > 0)) {
    throw new FormPreconditionError(
      'Cannot generate L-9: a NJ Estate Tax return is required (or estate tax is due). ' +
      'File Form IT-Estate instead; the Division issues waivers through that process.',
    );
  }
  // FND-L9A scope-limit (docs/IT-R-SPECIFICATION.md §1.2, §9): for a pre-2018 (L-9(A))
  // estate the "no NJ Estate Tax" determination above is computed from the NJ gross estate
  // ONLY. Adjusted taxable gifts and certain IRC §2011-code property are NOT modeled and
  // could raise the taxable estate over the filing threshold. That residual is surfaced to
  // the attorney as an explicit verification caveat (below) rather than silently assumed away.
  const estateThresholdCaveat =
    est !== null
      ? ' NOTE (L-9(A) scope): the "no NJ Estate Tax" determination is based on the NJ gross ' +
        'estate only and does NOT account for adjusted taxable gifts or certain IRC §2011-code ' +
        'property. For an estate approaching the ' +
        `$${est.exemptionThreshold.toLocaleString('en-US')} threshold, the attorney must ` +
        'independently confirm no NJ Estate Tax return is required before relying on this affidavit.'
      : '';

  const requiredAttachments = formDesignation === 'L-9(A)'
    ? [...COMMON_ATTACHMENTS, ...L9A_ADDITIONAL_ATTACHMENTS]
    : COMMON_ATTACHMENTS;

  // For L-9 (post-2018) a trust does not absolutely bar the form, but the Division may
  // require a full return if the trust terms indicate possible Inheritance Tax.
  const trustCaveat = matter.trustExists && formDesignation === 'L-9'
    ? ' NOTE: a trust exists — the Division may require a full return if the trust terms indicate ' +
      'possible Inheritance Tax, in which case no waiver issues from this form.'
    : '';
  const filingNote = FILING_NOTE + trustCaveat + estateThresholdCaveat;

  return {
    formDesignation,
    decedentLastName: matter.decedent.lastName,
    decedentFirstName: matter.decedent.firstName,
    ...(matter.decedent.middleName !== undefined
      ? { decedentMiddleName: matter.decedent.middleName }
      : {}),
    decedentSSN: matter.decedent.ssn,
    dateOfDeath: matter.decedent.dateOfDeath,
    countyOfResidence: matter.decedent.countyOfResidence,
    testate: matter.willExists,

    representative: matter.personalRepresentative,
    beneficiaries,
    realProperties,

    requiredAttachments,
    mailingAddress: MAILING_ADDRESS,
    filingNote,
    citation: CITATION,

    approvedCheckpointId: approvedCheckpoint.checkpointId,
    disclaimer: DISCLAIMER,
    generatedAt: new Date().toISOString(),
  };
}
